name: Question
description: Ask a question about opamp-go
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please provide as much context as possible.

  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please provide a clear and concise description of your question.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any additional context that might help us understand your question better.
      placeholder: |
        - What are you trying to achieve?
        - What have you already tried?
        - What documentation have you consulted?

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of opamp-go are you using?
      placeholder: "e.g., v0.13.0"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: |
        - OS: [e.g. Windows 10, macOS 13.0, Ubuntu 20.04]
        - Go version: [e.g. 1.21.0]
        - Architecture: [e.g. amd64, arm64]

  - type: textarea
    id: code-example
    attributes:
      label: Code example
      description: If applicable, provide a code example or relevant configuration.
      render: go

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0